version: "2.4"
services:
  php:
    build: ./Docker/php
    volumes:
      - "./:/var/www/html"
      - "./Docker/php/php.ini:/usr/local/etc/php/php.ini"
    links:
      - db
      - es01

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento_password
      - MYSQL_DATABASE=magento
    volumes:
      - ./dist/mysql:/var/lib/mysql

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./Docker/nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./Docker/nginx/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./Docker/nginx/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./Docker/nginx/dhparam.pem:/etc/nginx/dhparam.pem
      - ./Docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./dist/elasticsearch:/usr/share/elasticsearch/data